# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
name: Python Package using Conda

on: [commit_comment]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
  # Чекаутим код
    - uses: actions/checkout@master
     # Устанавливаем python нужной версии
    - uses: actions/setup-python@v1
      with:
       python-version: '3.10'
       architecture: 'x64'
    - name: Install requirements
     # Устанавливаем зависимости
      run: pip install -r requirements.txt
    - name: Run tests
      run: coverage run DevTools 5/TestCalc.py
    - name: Tests report
      run: coverage report
          conda install pytest
          pytest

