name: Python application
on:
  push:
    branches:
    - main

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements.txt
        # Устанавливаем зависимости
        run: pip install DevTools 5/ requirements.txt
      - name: Run tests
        # Запускаем тесты
        run: coverage run DevTools 5/TestCalc.py
      - name: Tests report
        run: coverage report

